#!/bin/bash

function r-path() {
    if which realpath &> /dev/null; then
        realpath $1
    else
        readlink -f $1
    fi
}

ZWORK_DIR=$(dirname $(dirname $(r-path $0)));
ZWAR_NAME=zman.war
ZPORT=
cd $ZWORK_DIR;

while [[ $# -gt 0 ]]; do
    case $1 in

        -f|--foreground)
            echo "Run in foreground" # need for docker
            FOREGROUND=true
            shift
            ;;

        -p=*|--port=*)
            echo "Use port "$2
            ZPORT="$2"
            shift 2
            ;;

        start)
            ACTION="start"
            shift
            ;;

        stop)
            ACTION="stop"
            shift
            ;;

        *)
            echo "Usage: zman <start|stop> [-p|--port]"
            echo "    start -p=8888 - start zman on specified port (default 8080)"
            echo "    stop  - stop running zman"
            echo
            ;;
    esac
done

RUN_LINE=

if [[ "$ZPORT" == "" ]]; then
    RUN_LINE="java -jar $ZWORK_DIR/zman.war > $ZWORK_DIR/log/zman.log 2>&1"
else
    RUN_LINE="java -jar $ZWORK_DIR/zman.war --server.port=$ZPORT > $ZWORK_DIR/log/zman.log 2>&1"
fi

function zmanPid() {
    ps aux | grep zman | grep war | grep -v grep | grep -P '^\d+'
}

function start {
    if [[ "$(jps | grep zman.war)" ]]; then
        echo "Already running"
        exit
    fi

    if [ $FOREGROUND ]; then
	    $RUN_LINE
    else
	    nohup $RUN_LINE &
    fi
    echo "Started"
}

function stop {
    if [[ -z "$(zmanPid)" ]]; then
        echo "Zman is not running" >&2
        exit
    fi
    kill -9 $(zmanPid) > /dev/null 2>&1
    echo "Stopped"
}

case $ACTION in
    start)
    echo "start"
    start
    ;;
    stop)
    echo "stop"
    stop
    ;;
    *)
    ;;
esac