spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: "jdbc:h2:file:./db/zk-storage/ZKStorage"
  jackson:
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false

logging.level:
  org.apache.zookeeper: WARN

audit:
  enabled: true

zman:
  cache:
    max-elements: 20
    time-to-idle-seconds: 1800
    eviction-delay-seconds: 60
  curator:
    retries: 2
    sleep-time-between-retries-millis: 1000

authentication:
  type: NONE
server:
  session:
    timeout: 1200
#  ad:
#    domain: "operator.ru"
#    url: "ldap://dc.operator.ru/"
#
#  ldap:
#    base: "dc=operator,dc=ru"
#    url: "ldap://dc.operator.ru:389"
#
#    #may be empty if userSearchFilter & userSearchBase are set
#    userDnPatterns:
#      - "uid={0},ou=people"
#
#    #may be empty if userDnPatterns is set
#    #userDN: "cn=administrator,ou=people"
#    #userPassword: "pwd"
#    userSearchFilter: "(uid={0})"
#    userSearchBase: "ou=people"
#
#  kerberos:
#    servicePrincipal: tomcat/server.domain.com@DOMAIN.COM
#    keytabFilePath: /some/path/tomcat.keytab
---

spring:
  profiles: dev
frontend:
  path: "zman-frontend/target/frontend"

